'use client'

import { useMemo, useState, type CSSProperties } from 'react'
import styles from './page.module.css'

const defaults = { titleSize: 20, titleLeading: 1.05, titleTracking: 0, titleBottom: 8, subtitleSize: 16, subtitleLeading: 1.65, subtitleTracking: 0, subtitleTop: 8, metaSize: 13, metaLeading: 1.4, metaTracking: 0, metaTop: 8, bodySize: 18, bodyLeading: 1.6, bodyTracking: 0, paragraphSpace: 24, h1Size: 40, h1Weight: 400, h1Leading: 1, h1Tracking: 0, h1Top: 48, h1Bottom: 20, h2Size: 28, h2Weight: 400, h2Leading: 1, h2Tracking: 0, h2Top: 32, h2Bottom: 12, h3Size: 24, h3Weight: 400, h3Leading: 1, h3Tracking: 0, h3Top: 24, h3Bottom: 16, h4Size: 18, h4Weight: 500, h4Leading: 1.2, h4Tracking: 0, h4Top: 20, h4Bottom: 12, linkTracking: 0, boldWeight: 600, listSpace: 24, listIndent: 24, listItemGap: 8, quoteSize: 18, quoteLeading: 1.55, quoteTracking: 0, quoteIndent: 20, quoteSpace: 32, codeSize: 14, codeLeading: 1.5, codePadding: 20, codeSpace: 32, tableSize: 15, tableLeading: 1.5, tablePadding: 10, captionSize: 14, captionLeading: 1.4, captionTracking: 0, captionTop: 10, calloutSize: 12, calloutTracking: 1, calloutSpace: 10 } as const
type SettingKey = keyof typeof defaults
type Control = { label: string; key: SettingKey; min: number; max: number; step: number; unit: string }
const c = (label: string, key: SettingKey, min: number, max: number, step: number, unit = ''): Control => ({ label, key, min, max, step, unit })
const headings = (prefix: 'h1' | 'h2' | 'h3' | 'h4') => [c('Size', `${prefix}Size`, 16, 64, 1, 'px'), c('Weight', `${prefix}Weight`, 300, 700, 100), c('Line height', `${prefix}Leading`, .85, 1.5, .05), c('Letter spacing', `${prefix}Tracking`, -6, 4, .25, '%'), c('Space above', `${prefix}Top`, 0, 128, 4, 'px'), c('Space below', `${prefix}Bottom`, 0, 48, 2, 'px')] as Control[]
const groups: Array<[string, Control[]]> = [
  ['Article header', [c('Article title — size', 'titleSize', 14, 48, 1, 'px'), c('Article title — leading', 'titleLeading', .9, 1.5, .05), c('Article title — tracking', 'titleTracking', -6, 4, .25, '%'), c('Article title — space below', 'titleBottom', 0, 40, 2, 'px'), c('Subtitle — size', 'subtitleSize', 12, 28, 1, 'px'), c('Subtitle — leading', 'subtitleLeading', 1.2, 2, .05), c('Subtitle — tracking', 'subtitleTracking', -3, 3, .25, '%'), c('Subtitle — space above', 'subtitleTop', 0, 32, 2, 'px'), c('Metadata — size', 'metaSize', 10, 20, 1, 'px'), c('Metadata — leading', 'metaLeading', 1, 2, .05), c('Metadata — tracking', 'metaTracking', -3, 3, .25, '%'), c('Metadata — space above', 'metaTop', 0, 32, 2, 'px')]],
  ['Body copy', [c('Font size', 'bodySize', 14, 24, 1, 'px'), c('Line height', 'bodyLeading', 1.2, 2, .05), c('Letter spacing', 'bodyTracking', -3, 3, .25, '%'), c('Paragraph gap', 'paragraphSpace', 0, 48, 2, 'px')]], ['Markdown H1', headings('h1')], ['Heading 2', headings('h2')], ['Heading 3', headings('h3')], ['Heading 4', headings('h4')], ['Links', [c('Letter spacing', 'linkTracking', -3, 3, .25, '%')]], ['Bold & italic', [c('Bold weight', 'boldWeight', 400, 800, 100)]], ['Lists', [c('Vertical spacing', 'listSpace', 0, 48, 2, 'px'), c('Indentation', 'listIndent', 0, 64, 2, 'px'), c('Item gap', 'listItemGap', 0, 32, 2, 'px')]], ['Blockquote', [c('Font size', 'quoteSize', 14, 28, 1, 'px'), c('Line height', 'quoteLeading', 1.2, 2, .05), c('Letter spacing', 'quoteTracking', -3, 3, .25, '%'), c('Indentation', 'quoteIndent', 0, 64, 2, 'px'), c('Vertical spacing', 'quoteSpace', 0, 64, 2, 'px')]], ['Inline code & Code block', [c('Font size', 'codeSize', 11, 20, 1, 'px'), c('Line height', 'codeLeading', 1.1, 2, .05), c('Block padding', 'codePadding', 0, 48, 2, 'px'), c('Block spacing', 'codeSpace', 0, 64, 2, 'px')]], ['Tables', [c('Font size', 'tableSize', 11, 22, 1, 'px'), c('Line height', 'tableLeading', 1.1, 2, .05), c('Cell padding', 'tablePadding', 0, 24, 1, 'px')]], ['Captions', [c('Font size', 'captionSize', 11, 20, 1, 'px'), c('Line height', 'captionLeading', 1.1, 2, .05), c('Letter spacing', 'captionTracking', -3, 3, .25, '%'), c('Space above', 'captionTop', 0, 32, 2, 'px')]], ['Callout label', [c('Font size', 'calloutSize', 10, 20, 1, 'px'), c('Letter spacing', 'calloutTracking', -1, 4, .25, '%'), c('Space below', 'calloutSpace', 0, 32, 2, 'px')]],
]
const kebab = (key: string) => key.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
const valueFor = (key: string, value: number) => key.endsWith('Tracking') ? `${value / 100}em` : key.endsWith('Leading') ? String(value) : `${value}px`
const articleVariable = (key: string) => `--article-${kebab(key).replace(/-(top|bottom)$/, '-$1-space')}`

export default function TypeSpecimen() {
  const [values, setValues] = useState<Record<SettingKey, number>>(defaults)
  const [copied, setCopied] = useState(false)
  const specimenStyle = useMemo(() => Object.fromEntries(Object.entries(values).map(([key, value]) => [`--specimen-${kebab(key)}`, valueFor(key, value)])) as CSSProperties, [values])
  const copyCss = async () => { await navigator.clipboard?.writeText(Object.entries(values).map(([key, value]) => `${articleVariable(key)}: ${valueFor(key, value)};`).join('\n')); setCopied(true) }
  return <main className={styles.page}><aside className={styles.controls}><p className={styles.eyebrow}>Temporary tool</p><h1>Markdown Typography</h1><p className={styles.description}>Tune the full article system, then copy one set of values.</p>{groups.map(([name, group]) => <section key={name} className={styles.group}><h2>{name}</h2>{group.map((item) => <label key={item.key} className={styles.control}><span>{item.label}<output>{item.unit === '%' ? `${values[item.key] / 100}em` : `${values[item.key]}${item.unit}`}</output></span><input type="range" min={item.min} max={item.max} step={item.step} value={values[item.key]} onChange={(event) => setValues((current) => ({ ...current, [item.key]: Number(event.target.value) }))} /></label>)}</section>)}<button type="button" onClick={copyCss}>{copied ? 'Copied CSS values' : 'Copy CSS values'}</button></aside><article className={styles.specimen} style={specimenStyle}><header className={styles.articleHeader}><h1>Article title as page chrome</h1><p>A subtitle gives the reader context before they begin the article.</p><span>Jun 22, 2025 · Design systems</span></header><p className={styles.kicker}>A live Markdown specimen</p><h1>Markdown H1 establishes the central idea</h1><p>Typography is not decoration. It gives a reader a dependable rhythm through an idea, from a short <a href="#type">link within the text</a> to the most detailed explanation.</p><p>When a system is clear, its <strong>important details</strong> can carry weight without interrupting the flow. <em>That balance is the work.</em></p><h2>Heading two builds a section</h2><h3>Heading three provides detail</h3><h4>Heading four handles a small transition</h4><p>Good Markdown needs a small, legible set of decisions:</p><ol><li>Body copy for sustained reading</li><li>Headings that create a clear map</li><li>Lists that stay quiet but scannable</li></ol><blockquote>“The best interface is often the one that helps someone move through complexity without noticing the effort.”</blockquote><p>Use <code>intentional defaults</code> for values that appear in every article.</p><pre><code>{`const type = {\n  body: '18px / 1.6',\n  heading: '28px / 1',\n}`}</code></pre><table><thead><tr><th>Element</th><th>Purpose</th></tr></thead><tbody><tr><td>H2</td><td>Major section</td></tr><tr><td>H3</td><td>Supporting idea</td></tr></tbody></table><aside className={styles.callout}><strong>Note</strong><p>Callout labels should inform without interrupting.</p></aside><figure><div className={styles.figurePlaceholder}>Image / diagram</div><figcaption>Captions add context without competing with the article.</figcaption></figure></article></main>
}
